### ISSUE TITLE
Isolate individual merges in extended logging

### ISSUE THREAD

**Issue by bjendres** [systopia/de.systopia.xdedupe#2]
With extended logging, every change to the DB is logged. However, if you batch-merge a lot of contacts it will just be recorded as one big change.

Ideally we'd be able to mark every individual merge separately, e.g. by ``log_conn_id``.

**Comment by bjendres** [comment]
@eileen: you mentioned you had implemented something like this in your merge extension, right!?

**Comment by bjendres** [comment]
@eileenmcnaughton you mentioned you had implemented something like this in your merge extension, right!?

**Comment by eileenmcnaughton** [comment]
```
function wmf_civicrm_civicrm_merge($type, &$refs, $mainId, $otherId, $tables) {
  switch ($type) {
    case 'batch' :
    case 'form' :

      watchdog("civicrm_merge_debug", "Deduping contacts $mainId and $otherId");
      $refs['migration_info']['context'] = $type;
      CRM_Core_DAO::executeQuery('SET @uniqueID = %1', array(
        1 => array(
          uniqid() . CRM_Utils_String::createRandom(CRM_Utils_String::ALPHANUMERIC, 4),
          'String',
        ),
      ));
```
