### ISSUE TITLE
We don't see any Automation menus in Administer (on Wordpress?)

### ISSUE THREAD

**Issue by alexletizia** [systopia/de.systopia.xdedupe#23]
CiviCRM 5.52.3
Wordpress 6.1
PHP 7.4.32

**Comment by bjendres** [comment]
You'll first have to **save** a deduping configuration ("save as new"). Then the the link in the menu ("Administer" -> "Automation" -> "Extended Deduplication") takes you the configuration manager, where you can activate the automation steps.

**Comment by alexletizia** [comment]
let me explain better, in all CiviCRM no menu related to X-Dedupe appears to do "save a deduping configuration"

**Comment by bjendres** [comment]
> let me explain better, in all CiviCRM no menu related to X-Dedupe appears to do "save a deduping configuration".

I'm not sure I understand. Are you talking about the user menu or URL paths?

In any case: when you use the link in the menu ("Administer" -> "Automation" -> "Extended Deduplication") for the first time, it'll take you to the "control room" (civicrm/xdedupe/controlroom?reset=1). There you can experiment with, and eventually save a configuration (via button).

As soon as there is a saved configuration, the "configuration manager" is accessible via the menu link ("Administer" -> "Automation" -> "Extended Deduplication").

**Comment by alexletizia** [comment]
we believe that the extension is not activated because there is no menu item in Administer to be able to;

_"use the link in the menu (" Administer "->" Automation "->" Extended Deduplication ") for the first time, it'll take you to the "control room"_ 

Let's try disabling other extensions to make sure there isn't an incompatibility.

**Comment by bjendres** [comment]
> we believe that the extension is not activated because there is no menu item in Administer to be able to;

Does the extension show as "enabled" in the extension manager screen?

**Comment by alexletizia** [comment]
obviously yes

**Comment by alexletizia** [comment]
works only by using direct link at Control Room: civicrm/xdedupe/controlroom?reset=1

![X-dedupe issue 2](https://user-images.githubusercontent.com/40597363/200784126-9e7797fd-51c8-4d9d-a83f-7254ead7c935.png)

**Comment by bjendres** [comment]
Just a last thought: Could you try running a cache clear (``civicrm/menu/rebuild``), and see if that makes the menu appear?

**Comment by alexletizia** [comment]
no works also by:
- cleaning cache
- rebuild the CiviCRM menu
- rebuild the CiviCRM database triggers

**Comment by bjendres** [comment]
Strange....Thank you for reporting

**Comment by bjendres** [comment]
> controll room can be used (? we no still tested it)

Yes, the rest of the system should work, so far it just looks like the menu entries weren't added. You can do that manually for now :)

I'll keep this ticket open for somebody else to confirm the issue. This has certainly not happened on any of our (Drupal based) instances...

**Comment by alexletizia** [comment]
**does not work**: by filling in all the fields with a simple search for deduplication only on the surnames of the entire DB, clicking on "find" or "save new" redirects to the same link:

/ civicrm / xdedupe / controlroom /

This is likely to be due to the different URL structure of Wordpress.

**Comment by bjendres** [comment]
Interesting.

Can anyone confirm this behaviour on WordPress?

**Comment by alexletizia** [comment]
so it is difficult to get feedback from Wordpress users, it is not certain that there are wordpress users among the 35 users of the extension. Are you in contact with @kcristino who here on GhitHub is a true CiviCRM / Wordpress expert? Can you invite him to the discussion?

**Comment by kcristiano** [comment]
I agree on install the menu items are not created.  I ma give another test as the site I initially tested on uses php 8.0 and i had fatal errors on extension activation.   

I can manually add the menu item, but it should be created on activation.

I'll test on a clean php 7.4 install and report back

**Comment by bjendres** [comment]
Possible connection with #24

**Comment by bjendres** [comment]
@kcristiano is this solved by any chance?

**Comment by kcristiano** [comment]
@bjendres Yes  it is fixed.  I just tested on WP 6.2.2, CiviCRM - master (5.64.alpha), php 7.4.  xdedupe - master 1.2-dev

On a new install the expected menus appear.   I can get to the 'Control Rooom' after install and then after I save a rule the same menu link takes me to 'XDedupe Configuration Manager'

**Comment by bjendres** [comment]
Thanks for the feedback!
